const Projetos = [
  {
    "id" : "496e7465727669657720416c676f726974686d73",
    "nome": "Interview Algorithms",
    "picture":"https://github.com/LeandroTeixeira/Interview-Algorithms/raw/main/Container%20With%20Most%20Water/two-pointer.png",
    "link":"",
    "repositoryLink":"https://github.com/LeandroTeixeira/Interview-Algorithms",
    "descricao":`A repository with my solutions to different algorithm problems found around the internet. The idea is to sharp my skills for potential interviews in the future.
    Each folder deals with a specific problem. It will contain the source of the problem (when aplicable), a description of the problem and one or more solutions with their respective general descriptions, implementations, analysis of space and time complexity and an example of how the code performed when submitted at LeetCode.`,
    "languages":["Python"],
    "tecnologies":["Brute Force algorithms", "Divide-and-Conquer algorithms", "Two Pointer technique", "recursive algorithms", "Array Traversal problems"],
    "BGColor":"rgb(245, 245, 245)",
    "Color":"Black",
  },
  {
    "id" : "54756e6573",
    "nome": "Tunes",
    "picture":"",
    "link":"",
    "repositoryLink":"",
    "descricao":"",   
    "languages":["React","HTML", "CSS", "JavaScript"],
    "tecnologies":[],
    "BGColor":"#c0c0c0",
    "Color":"White",
  },
  {
    "id" : "5472756e666f",
    "nome": "Trunfo",
    "picture":"",
    "link":"",
    "repositoryLink":"",
    "descricao":"",    
    "languages":["React","HTML", "CSS", "JavaScript"],
    "tecnologies":[],
    "BGColor":"#c0c0c0",
    "Color":"White",
  },
  {
    "id" : "4f6e6c696e652053746f7265",
    "nome": "Online Store",
    "picture":"",
    "link":"",
    "repositoryLink":"",
    "descricao":"",
    "languages":["React","HTML", "CSS", "JavaScript"],
    "tecnologies":[],
    "BGColor":"#c0c0c0",
    "Color":"White",
  },
  {
    "id" : "506f6b65646578",
    "nome": "Pokedex",
    "picture":"",
    "link":"",
    "repositoryLink":"",
    "descricao":"",    
    "languages":["React","HTML", "CSS", "JavaScript"],
    "tecnologies":[],
    "BGColor":"#c0c0c0",
    "Color":"White",
  },
  {
    "id" : "506978656c20417274",
    "nome": "Pixel Art",
    "picture":"https://github.com/LeandroTeixeira/Pixel-Art/raw/main/print.png",
    "link":"https://leandroteixeira.github.io/Pixel-Art/",
    "repositoryLink":"https://github.com/LeandroTeixeira/Pixel-Art",
    "descricao":"Projeto de pixel art desenvolvido durante o módulo de Fundamentos do curso da Trybe. Trata-se de um projeto feito com HTML, CSS e JavaScript para a criação de pixel art. As cores são geradas de forma pseudo-aleatória sempre que a página é recarregada. São 4 tons, um na escala de preto e cinza, um tom de vermelho, um de verde e um de azul. As cores também podem ser modificadas durante o uso se o usuário assim desejar.",    
    "languages":["HTML", "CSS", "JavaScript"],
    "tecnologies":["Manipulação de DOM", "Geração de valores aleatórios"],
    "BGColor":"#c0c0c0",
    "Color":"White",
  },
  {
    "id" : "53686f7070696e672043617274",
    "nome": "Shopping Cart",
    "picture":"https://github.com/LeandroTeixeira/Shopping-Cart/raw/main/Image.png",
    "link":"https://leandroteixeira.github.io/Shopping-Cart/",
    "repositoryLink":"https://github.com/LeandroTeixeira/Shopping-Cart",
    "descricao":"Projeto que simula um carrinho de compras. Os elementos apresentados são obtidos através da API do MercadoLivre. Para esta aplicação também foram desenvolvidos uma série de testes em Jest para avaliar a qualidade do código. Os testes estão disponíveis na pasta 'testes' e foram desenvolvidos de modo a terem a maior cobertura possível do código.",   
    "languages":["HTML", "CSS", "JavaScript"],
    "tecnologies":["JS assíncrono", "Requisições a API","Testes com Jest"],
    "BGColor":"rgb(226, 226, 226)",
    "Color":"Black",
  }, 
  {
    "id" : "53697374656d6120536f6c6172",
    "nome": "Sistema Solar", 
     "picture":"https://github.com/LeandroTeixeira/Sistema-Solar/raw/main/Image.png",
    "link":"https://leandroteixeira.github.io/Sistema-Solar/",
    "repositoryLink":"https://github.com/LeandroTeixeira/Sistema-Solar",
    "descricao":"Trata-se de um projeto pequeno visando usar habilidades recém-adquiridas em React para exibir a lista dos planetas e suas missões espaciais.",   
    "languages":["React","HTML", "CSS", "JavaScript"],
    "tecnologies":["Uso de Props",
      "Criação e Desenvolvimento de Componentes em React",
"Uso de PropTypes para validação das props"],
    "BGColor":"#444",
    "Color":"White",
  },
  {
    "id" : "4c6972616373",
    "nome": "Liracs",
    "picture":"https://github.com/LeandroTeixeira/Liracs/raw/main/Image.png",
    "link":"",
"repositoryLink":"https://github.com/LeandroTeixeira/Liracs",
    "descricao":`Repositório referente ao software desenvolvido em grupo como TCC para o curso de Informática na instituição CEFET-MG no ano de 2015. Trata-se de um software desenvolvido em Java para executar instruções no computador a partir de comandos de voz.
O objetivo do software era, acima de tudo, desenvolver uma ferramenta de acessibilidade para pessoas com mobilidade reduzida que poderiam ter dificuldade de usar o computador.`,
  "languages":["Java"],
  "tecnologies":[
    "Bancos de dados implementados em Postgres",
    "Conceitos de MVC, incluindo mas não se limitando a Stubs, Skeletons e DAOs",
    "Interface gráfica desenvolvida com as ferramentas nativas de Java",
    "Gerenciamento de usuários via banco de dados",
    "Manipulação de áudio usando o pacote javax.sound"
  ],
  "BGColor":"rgb(85, 201, 201)",
  "Color":"Black",
  },
  
];

export default Projetos;